name: Backend Tests

on:
  push:
    branches:
      - main
      - develop
    paths:
      - projects/backend/**
      - .github/workflows/backend-tests.yml
      - .github/workflows/reusable-backend-tests.yml
  pull_request:
    branches:
      - main
      - develop
    paths:
      - projects/backend/**
      - .github/workflows/backend-tests.yml
      - .github/workflows/reusable-backend-tests.yml

permissions:
  contents: read

jobs:
  backend-tests:
    uses: ./.github/workflows/reusable-backend-tests.yml
