name: frontend-tests

on:
  push:
    branches:
      - main
      - develop
    paths:
      - projects/frontend/**
      - .github/workflows/frontend-tests.yml
      - .github/workflows/frontend-test-suite.yml
      - .nvmrc
  pull_request:
    branches:
      - main
      - develop
    paths:
      - projects/frontend/**
      - .github/workflows/frontend-tests.yml
      - .github/workflows/frontend-test-suite.yml
      - .nvmrc

permissions:
  contents: read

jobs:
  frontend-tests:
    name: Frontend test suite
    uses: ./.github/workflows/frontend-test-suite.yml
    with:
      node-version-file: .nvmrc
