name: frontend-tests

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'projects/frontend/**'
      - '.github/workflows/frontend-tests.yml'
      - '.github/workflows/reusable-frontend-tests.yml'
      - '.nvmrc'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'projects/frontend/**'
      - '.github/workflows/frontend-tests.yml'
      - '.github/workflows/reusable-frontend-tests.yml'
      - '.nvmrc'

permissions:
  contents: read

jobs:
  frontend-tests:
    uses: ./.github/workflows/reusable-frontend-tests.yml
